[project]
name = "lique"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "polars>=1.17.1",
    "tqdm>=4.67.1",
]

[tool.ruff.format]
exclude = ["convert_to_qasm.py"]
