[package]
name = "lique_ls"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.41.1", features = [
    "io-util",
    "macros",
    "net",
    "rt",
    "rt-multi-thread",
] }
anyhow = "1.0.93"
lsp-types = "0.97.0"
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.132"
